
server:
  port: 8004
eureka:
  instance:
    instance-id: gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/  # 注册中心访问地址

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
          locator:
            enabled: true
      routes:
        - id: first
          uri: lb://CONSUMERSERVICE
          predicates:
            - Path=/demo/**
logging:
  level:
    org.springframework.cloud.gateway: debug